# Generated by Django 3.1.5 on 2021-02-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210217_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default="Hello, I'm a new user!", max_length=120),
        ),
    ]
